FROM node:21.2.0-alpine3.17

RUN apk update && apk upgrade && \
		apk add --no-cache --virtual .gyp python3 make g++ libtool autoconf automake git openssh tini

WORKDIR /app

COPY . .

RUN npm install

EXPOSE 3000

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["npm","run","start:dev"]