version: '3'
services:
  main:
    container_name: todo-service
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '80:3000'
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
      - ~/.config:/root/.config
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres
    container_name: todo_app_db
    restart: always
    ports:
      - '6001:5432'
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
    driver: local