version: '3'
services:
  main:
    container_name: todo-service
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '80:3000'
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
      - ~/.config:/root/.config
    env_file:
      - .env